close all;
clear variables;
clc;

% Prepare the training dataset:
dir_training = 'Stenosis608_PGM_Partitioned/Training/';
dataset_training = imageDatastore(dir_training, ...
                                  "IncludeSubfolders", true, ...
                                  "LabelSource", "foldernames");

% Split the training dataset for validation during training:
[imgs_train, imgs_val] = splitEachLabel(dataset_training, 0.9, 0.1, 'randomized');

% Prepare the testing dataset:
dir_testing = 'Stenosis608_PGM_Partitioned/Testing/';
dataset_testing = imageDatastore(dir_testing, ...
                                  "IncludeSubfolders", true, ...
                                  "LabelSource", "foldernames");


% Load an image to extract its size:
img = imread([dir_training, 'Positive/002_Positive.pgm']);
image_size = size(img);

% Set the max train epochs:
max_train_epochs = 1000;

% Configure training parameters:
cnn_train_options = trainingOptions('adam', ...
                                    'InitialLearnRate',     0.001, ...
                                    'MaxEpochs',            max_train_epochs, ...
                                    'MiniBatchSize',        16, ...
                                    'Shuffle',              'every-epoch', ...
                                    'ValidationData',       imgs_val, ...
                                    'ValidationFrequency',  50, ...
                                    'Verbose',              true);

% Build the CNN model:
cnnmodel=[
            imageInputLayer(image_size), ...
            convolution2dLayer(5, 2, 'Padding', 'same', 'Stride', 2), ...
            batchNormalizationLayer(), ...
            leakyReluLayer(), ...
            convolution2dLayer(3, 16, 'Padding', 'same', 'Stride', 2), ...
            reluLayer(), ...
            convolution2dLayer(3, 16, 'Padding', 'same', 'Stride', 2), ...
            batchNormalizationLayer(), ...
            leakyReluLayer(), ...
            dropoutLayer(0.5), ...
            maxPooling2dLayer([2, 2], 'Padding', 'same'), ...
            convolution2dLayer(1, 16, 'Padding', 'same', 'Stride', 2), ...
            flattenLayer(), ...
            fullyConnectedLayer(2), ...
            softmaxLayer(), ...
            classificationLayer()
        ];

% Uncomment next line to show the full model information:
%analyzeNetwork(cnnmodel(1:numel(cnnmodel)-1));

% Train the CNN model:
[cnnmodel_trained, t_info] = trainNetwork(imgs_train, cnnmodel, cnn_train_options);    

% Test the model with an image:
predicted_label = classify(cnnmodel_trained, img);

% Evaluamos la exactitud de la CNN entrenada previamente con 
% el conjunto de Testing:
labels_original_test = categorical(numel(dataset_testing.Files), 1);
labels_original_test(1:64, 1) = {'Negative'};
labels_original_test(65:128, 1) = {'Positive'};
[labels_predicted_test, scores_test] = classify(cnnmodel_trained, dataset_testing, ...
                                     "MiniBatchSize", cnn_train_options.MiniBatchSize);
accuracy_test = sum(labels_predicted_test == labels_original_test) / numel(labels_original_test);

disp(['Accuracy in Testing:', num2str(accuracy_test)]);